### ISSUE TITLE
Agreement URL has changed 

### ISSUE THREAD

**Issue by ldvc** [Spredzy/lecm#56]
On a fresh install, got this error:
```
ERROR:lecm.certificate:[host.example.com] b'Parsing account key...\nParsing CSR...\nRegistering account...\nTraceback (most recent call last):\n  File "/usr/bin/acme-tiny", line 11, in <module>\n    load_entry_point(\'acme-tiny==20160326\', \'console_scripts\',
 \'acme-tiny\')()\n  File "/usr/lib/python3/dist-packages/acme_tiny.py", line 208, in __entry_point\n    main(sys.argv[1:])\n  File "/usr/lib/python3/dist-packages/acme_tiny.py", line 194, in main\n    signed_crt = get_crt(args.account_key, args.csr, args.acm
e_dir, log=LOGGER, CA=args.ca)\n  File "/usr/lib/python3/dist-packages/acme_tiny.py", line 92, in get_crt\n    raise ValueError("Error registering: {0} {1}".format(code, result))\nValueError: Error registering: 400 b\'{\\n  "type": "urn:acme:error:malformed",
\\n  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",\\n  "status": 400\\n}\'\n'
```
Probably a change on LE side ?

**Comment by sbadia** [comment]
Hi @ldvc,
Thanks for this bug report!

Indeed, agreement url was changed, and this new url was updated in `acme-tiny` (https://github.com/diafygi/acme-tiny/commit/c4940d229a296b7643e86d2e9ab31a6e0099ba71)

You installed lecm with `pip`, `apt` or something else ?

**Comment by ldvc** [comment]
Hi @sbadia,

yes... I discovered after opening this issue that was related to `acme-tiny` and manually changed new agreement file. Modification made in https://github.com/diafygi/acme-tiny/commit/c4940d229a296b7643e86d2e9ab31a6e0099ba71 is much more elegant!

I installed lecm via apt on Debian Stretch:
```
user@server:~ $ dpkg -l lecm
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-==================================================
ii  lecm                   0.0.7-1          all              Let's Encrypt Certificate Manager
```

**Comment by sbadia** [comment]
Ok, the version in Debian is impacted, a bug was already raised on Debian side <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882693>

```
❯ rmadison acme-tiny
acme-tiny  | 20160801-3~bpo8+1 | jessie-backports | source, all
acme-tiny  | 20160801-3        | stable           | source, all
acme-tiny  | 20160801-3        | testing          | source, all
acme-tiny  | 20160801-3        | unstable         | source, all
```

I'll take a look on Debian side :)

**Comment by sbadia** [comment]
Hi!

Just for the record (fixed in buster, stretch)
* https://tracker.debian.org/news/892115
* https://tracker.debian.org/news/937398
